### ISSUE TITLE
Cannot install on Kali Linux / No commands when manually compiled

### ISSUE THREAD

**Issue by rootabeta** [NerdOfCode/Restricted-Shell#13]
Attempting to run `bash run.sh` yields an error reading "run.sh: line 71: Kali GNU/Linux: No such file or directory." By copying into the Src directory and compiling with `gcc shell.c globals.h -o rshell` and running with `./rshell` results in no commands being executable aside from the "cmds" command.

**Comment by NerdOfCode** [comment]
Please open `Src/globals.h` and enable `DEBUG`! Then run some commands and report back on the output please!

Edit: Kali Linux is also not officially supported

**Comment by rootabeta** [comment]
> Please open `Src/globals.h` and enable `DEBUG`! Then run some commands and report back on the output please!
> 
> Edit: Kali Linux is also not officially supported
Did what you said, here's the output. 
Command Not Found!
sh: 1: /etc/Restricted-Shell/Bin/pwd: not found
Command: ls
command_args: True
Command Not Found!
sh: 1: /etc/Restricted-Shell/Bin/ls: not found
Command: version
command_args: True
Command Not Found!
sh: 1: /etc/Restricted-Shell/Bin/version: not found
Command: 

Trying to copy into /etc/Restricted-Shell/ provides a missing directory. Making this dir and compiling everything in Restricted-Shell/Bin/cmd_src and copying everything into that dir makes... a mess.

Error: 1005
 root@root[Src] root@root[Src] --snip-- root@root[Src].
PS: I know Kali isn't officially supported, but then again, the hacker in me fails to care ;)

**Comment by NerdOfCode** [comment]
Feel free to create a pull request that solves this problem👍

**Comment by rootabeta** [comment]
What a... professional... solution.
