### ISSUE TITLE
Vulnerability

### ISSUE THREAD

**Issue by NerdOfCode** [NerdOfCode/Restricted-Shell#4]
A non-admin user within the R-Shell can potentially gain admin access if they modify the source files... They can do so by running something similar to:

```shell
nano /etc/Restricted-Shell/cmd_src/...
```

**Comment by NerdOfLinux** [comment]
I think you meant the title to be "**Vulne**rability", not "**Vulre**nability"

**Comment by NerdOfCode** [comment]
In latest push, you can't directory cd into the `/etc/Restricted-Shell/` Directory, but you can still access the sub-dirs of the parent...

**Comment by NerdOfCode** [comment]
Patched! 🥇
