### ISSUE TITLE
README.md recommendations 

### ISSUE THREAD

**Issue by NerdOfLinux** [NerdOfCode/Restricted-Shell#5]
## /etc/passwd

Please **DO NOT** directly edit `/etc/passwd`, as this can **break** your OS. Instead, please recommend using the built-in `chsh` command:

```shell
sudo chsh [desired user] -s /etc/Restricted-Shell/run.sh
````
Also, this allows for you to change your own shell without being root.

## Location
Storing executables in `/etc/` is not standard, and probably not a good idea. Instead, please use `/usr/local/`:

> The `/usr/local` hierarchy is for use by the system administrator when installing software locally. It needs to be safe from being overwritten when the system software is updated. It may be used for programs and data that are shareable among a group of hosts, but not found in /usr.

[source](https://www.centos.org/docs/5/html/5.1/Deployment_Guide/s3-filesystem-usr-local.html)

**Comment by NerdOfCode** [comment]
I appreciate the advice... But I think you should rethink both "recommendations". For the first one, I was merely hinting at editing the `/etc/passwd/` file... 

And for the second statement... It is not a common "executable" ***file***... This is a multi-file program that is designed to be a fully equipped shell... The `/usr/local/` file is rather just a directory that is meant and designed for personal use...

Again, using the `/etc` directory enables enhanced compatibility between most Linux systems!
