### ISSUE TITLE
Bin/nano is using rnano instead of nano

### ISSUE THREAD

**Issue by NerdOfLinux** [NerdOfCode/Restricted-Shell#6]
In Bin/nano, the script checks the location of `rnano`, and then runs it. However, there is no point in doing this as `rnano` is just a symbolic link to `nano`:

```shell
file $(which rnano)
```
returns:
```shell
/bin/rnano: symbolic link to nano
```
which is just `/bin/nano`:
```shell
file /bin/nano
```
returns:
```shell
/bin/nano: ELF 64-bit LSB executable, x86-64, version 1 (SYSV), dynamically linked, interpreter /lib64/ld-linux-x86-64.so.2, for GNU/Linux 2.6.32, BuildID[sha1]=e87c5ab33de1e9e225244efd8e2a03f55892c98f, stripped
```

**Comment by NerdOfCode** [comment]
Although they may appear to be linked... They are unique in their own fashions... I recommend running
`man rnano`
and
`man nano`
And plus this enabled enhanced compatibility on separate systems!
