### ISSUE TITLE
Incorrect permissions

### ISSUE THREAD

**Issue by NerdOfLinux** [NerdOfCode/Restricted-Shell#7]
After cloning the repository, the source files in `Src` have weird permissions on them: executable. ".c" and ".h" files cannot be run directly, and should therefore not have executable permissions by default.
> The purpose of the "execute" permission is two-fold: 1) to tell the operating system which files are programs, and 2) to tell the user which programs they can run.

[source](https://security.stackexchange.com/a/66556)
The files in `Src` fit neither of the above, and should therefore not have execute permissions.

**Comment by NerdOfCode** [comment]
Fixed
